import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import Navbar from '@/components/Navbar'
import Providers from '@/components/Providers'
import { Toaster } from 'sonner'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn('relative font-sans antialiased',
       inter.className)}>
        <main className='min-h-screen relative flex flex-col '>
        <Providers>
        <Navbar />
        {children}
        </Providers>
        </main>
        <Toaster position='top-center' richColors />
        </body>
    </html>
  )
}
