// /* tslint:disable */
// /* eslint-disable */
// /**
//  * This file was automatically generated by Payload.
//  * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
//  * and re-run `payload generate:types` to regenerate this file.
//  */

// export interface Config {
//   collections: {
//     users: User;
//     property: Property;
//     media: Media;
//     orders: Order;
//     property_files: PropertyFile;
//     workers: Worker;
//     Tenant: Tenant;
//     Tenant1: Tenant1;
//     Announce: Announce;
//     TenantM: TenantM;
//     'payload-preferences': PayloadPreference;
//     'payload-migrations': PayloadMigration;
//   };
//   globals: {};
// }
// export interface User {
//   id: string;
//   products?: (string | Property)[] | null;
//   product_files?: (string | PropertyFile)[] | null;
//   role: 'admin' | 'user';
//   updatedAt: string;
//   createdAt: string;
//   email: string;
//   resetPasswordToken?: string | null;
//   resetPasswordExpiration?: string | null;
//   salt?: string | null;
//   hash?: string | null;
//   _verified?: boolean | null;
//   _verificationToken?: string | null;
//   loginAttempts?: number | null;
//   lockUntil?: string | null;
//   password: string | null;
// }
// export interface Property {
//   id: string;
//   user?: (string | null) | User;
//   Company_name: string;
//   Manager_full_name: string;
//   Comapany_Contact_number: string;
//   name: string;
//   unit_building: string;
//   unit_category: string;
//   Unit_name: string;
//   description?: string | null;
//   Payment_type: 'Rent' | 'Buy';
//   price: number;
//   Property_type: 'Housings' | 'Real Estate';
//   state: string;
//   Bedrooms: number;
//   Days: string;
//   property_files: string | PropertyFile;
//   approvedForSale?: ('pending' | 'approved' | 'denied') | null;
//   images: {
//     images: string | Media;
//     id?: string | null;
//   }[];
//   updatedAt: string;
//   createdAt: string;
// }
// export interface PropertyFile {
//   id: string;
//   user?: (string | null) | User;
//   updatedAt: string;
//   createdAt: string;
//   url?: string | null;
//   filename?: string | null;
//   mimeType?: string | null;
//   filesize?: number | null;
//   width?: number | null;
//   height?: number | null;
// }
// export interface Media {
//   id: string;
//   user?: (string | null) | User;
//   updatedAt: string;
//   createdAt: string;
//   url?: string | null;
//   filename?: string | null;
//   mimeType?: string | null;
//   filesize?: number | null;
//   width?: number | null;
//   height?: number | null;
//   sizes?: {
//     thumbnail?: {
//       url?: string | null;
//       width?: number | null;
//       height?: number | null;
//       mimeType?: string | null;
//       filesize?: number | null;
//       filename?: string | null;
//     };
//     card?: {
//       url?: string | null;
//       width?: number | null;
//       height?: number | null;
//       mimeType?: string | null;
//       filesize?: number | null;
//       filename?: string | null;
//     };
//     tablet?: {
//       url?: string | null;
//       width?: number | null;
//       height?: number | null;
//       mimeType?: string | null;
//       filesize?: number | null;
//       filename?: string | null;
//     };
//   };
// }
// export interface Order {
//   id: string;
//   _isPaid: boolean;
//   user: string | User;
//   Status: 'Paid' | 'Processing' | 'Failed' | 'Renewed';
//   products: (string | Property)[];
//   updatedAt: string;
//   createdAt: string;
// }
// export interface Worker {
//   id: string;
//   user?: (string | null) | User;
//   Full_name: string;
//   Phone_number: string;
//   Working_field: string;
//   updatedAt: string;
//   createdAt: string;
// }
// export interface Tenant {
//   id: string;
//   user?: (string | null) | User;
//   Full_name: string;
//   Phone_number: string;
//   Gender: string;
//   Adress: string;
//   City: string;
//   State: string;
//   products: (string | Property)[];
//   updatedAt: string;
//   createdAt: string;
// }
// export interface Tenant1 {
//   id: string;
//   Full_name: string;
//   Phone_number: string;
//   Adress: string;
//   Email: string;
//   City: string;
//   State: string;
//   Unit_name: string;
//   Unit_building: string;
//   Unit_category: string;
//   updatedAt: string;
//   createdAt: string;
// }
// export interface Announce {
//   id: string;
//   Email: string;
//   Subject: string;
//   Message: string;
//   updatedAt: string;
//   createdAt: string;
// }
// export interface TenantM {
//   id: string;
//   Email: string;
//   Subject: string;
//   Date: string;
//   Message: string;
//   updatedAt: string;
//   createdAt: string;
// }
// export interface PayloadPreference {
//   id: string;
//   user: {
//     relationTo: 'users';
//     value: string | User;
//   };
//   key?: string | null;
//   value?:
//     | {
//         [k: string]: unknown;
//       }
//     | unknown[]
//     | string
//     | number
//     | boolean
//     | null;
//   updatedAt: string;
//   createdAt: string;
// }
// export interface PayloadMigration {
//   id: string;
//   name?: string | null;
//   batch?: number | null;
//   updatedAt: string;
//   createdAt: string;
// }


// declare module 'payload' {
//   export interface GeneratedTypes extends Config {}
// }